name: movie
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
